config/routes.rb
Rails.application.routes.draw do
  resources :ingesters
  resources :stargate_manual_overrides
  resources :stargates
  resources :north_stars
  resources :star_nodes
  resources :solar_systems
  resources :galaxies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/star_node.rb
class StarNode < ApplicationRecord
  has_one :data_source
  has_one :current_status
  has_many :blockers
  has_many :blocking
  has_many :next
  has_many :previous
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/star_nodes_controller.rb
class StarNodesController < ApplicationController
  before_action :set_star_node, only: %i[ show edit update destroy ]

  # GET /star_nodes or /star_nodes.json
  def index
    @star_nodes = StarNode.all
  end

  # GET /star_nodes/1 or /star_nodes/1.json
  def show
  end

  # GET /star_nodes/new
  def new
    @star_node = StarNode.new
  end

  # GET /star_nodes/1/edit
  def edit
  end

  # POST /star_nodes or /star_nodes.json
  def create
    @star_node = StarNode.new(star_node_params)

    respond_to do |format|
      if @star_node.save
        format.html { redirect_to @star_node, notice: "Star node was successfully created." }
        format.json { render :show, status: :created, location: @star_node }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @star_node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /star_nodes/1 or /star_nodes/1.json
  def update
    respond_to do |format|
      if @star_node.update(star_node_params)
        format.html { redirect_to @star_node, notice: "Star node was successfully updated." }
        format.json { render :show, status: :ok, location: @star_node }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @star_node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /star_nodes/1 or /star_nodes/1.json
  def destroy
    @star_node.destroy
    respond_to do |format|
      format.html { redirect_to star_nodes_url, notice: "Star node was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_star_node
      @star_node = StarNode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def star_node_params
      params.require(:star_node).permit(:name, :description, :north_star_id)
    end
end

app/helpers/star_nodes_helper.rb
module StarNodesHelper
end

app/views/star_nodes/_form.html.erb
<%= form_with(model: star_node) do |form| %>
  <% if star_node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(star_node.errors.count, "error") %> prohibited this star_node from being saved:</h2>

      <ul>
        <% star_node.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :north_star_id %>
    <%= form.number_field :north_star_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/star_nodes/edit.html.erb
<h1>Editing Star Node</h1>

<%= render 'form', star_node: @star_node %>

<%= link_to 'Show', @star_node %> |
<%= link_to 'Back', star_nodes_path %>

app/views/star_nodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Star Nodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>North star</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @star_nodes.each do |star_node| %>
      <tr>
        <td><%= star_node.name %></td>
        <td><%= star_node.description %></td>
        <td><%= star_node.north_star_id %></td>
        <td><%= link_to 'Show', star_node %></td>
        <td><%= link_to 'Edit', edit_star_node_path(star_node) %></td>
        <td><%= link_to 'Destroy', star_node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Star Node', new_star_node_path %>

app/views/star_nodes/new.html.erb
<h1>New Star Node</h1>

<%= render 'form', star_node: @star_node %>

<%= link_to 'Back', star_nodes_path %>

app/views/star_nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @star_node.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @star_node.description %>
</p>

<p>
  <strong>North star:</strong>
  <%= @star_node.north_star_id %>
</p>

<%= link_to 'Edit', edit_star_node_path(@star_node) %> |
<%= link_to 'Back', star_nodes_path %>