config/routes.rb
Rails.application.routes.draw do
  resources :ingesters
  resources :stargate_manual_overrides
  resources :stargates
  resources :north_stars
  resources :star_nodes
  resources :solar_systems
  resources :galaxies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ingester.rb
class Ingester < ApplicationRecord
end

app/controllers/ingesters_controller.rb
class IngestersController < ApplicationController
  before_action :set_ingester, only: %i[ show edit update destroy ]

  # GET /ingesters or /ingesters.json
  def index
    @ingesters = Ingester.all
  end

  # GET /ingesters/1 or /ingesters/1.json
  def show
  end

  # GET /ingesters/new
  def new
    @ingester = Ingester.new
  end

  # GET /ingesters/1/edit
  def edit
  end

  # POST /ingesters or /ingesters.json
  def create
    @ingester = Ingester.new(ingester_params)

    respond_to do |format|
      if @ingester.save
        format.html { redirect_to @ingester, notice: "Ingester was successfully created." }
        format.json { render :show, status: :created, location: @ingester }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingesters/1 or /ingesters/1.json
  def update
    respond_to do |format|
      if @ingester.update(ingester_params)
        format.html { redirect_to @ingester, notice: "Ingester was successfully updated." }
        format.json { render :show, status: :ok, location: @ingester }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingesters/1 or /ingesters/1.json
  def destroy
    @ingester.destroy
    respond_to do |format|
      format.html { redirect_to ingesters_url, notice: "Ingester was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingester
      @ingester = Ingester.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingester_params
      params.fetch(:ingester, {})
    end
end

app/helpers/ingesters_helper.rb
module IngestersHelper
end

app/views/ingesters/_form.html.erb
<%= form_with(model: ingester) do |form| %>
  <% if ingester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingester.errors.count, "error") %> prohibited this ingester from being saved:</h2>

      <ul>
        <% ingester.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingesters/edit.html.erb
<h1>Editing Ingester</h1>

<%= render 'form', ingester: @ingester %>

<%= link_to 'Show', @ingester %> |
<%= link_to 'Back', ingesters_path %>

app/views/ingesters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingesters</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingesters.each do |ingester| %>
      <tr>
        <td><%= link_to 'Show', ingester %></td>
        <td><%= link_to 'Edit', edit_ingester_path(ingester) %></td>
        <td><%= link_to 'Destroy', ingester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingester', new_ingester_path %>

app/views/ingesters/new.html.erb
<h1>New Ingester</h1>

<%= render 'form', ingester: @ingester %>

<%= link_to 'Back', ingesters_path %>

app/views/ingesters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ingester_path(@ingester) %> |
<%= link_to 'Back', ingesters_path %>