config/routes.rb
Rails.application.routes.draw do
  resources :ingesters
  resources :stargate_manual_overrides
  resources :stargates
  resources :north_stars
  resources :star_nodes
  resources :solar_systems
  resources :galaxies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/galaxy.rb
class Galaxy < ApplicationRecord
end

app/controllers/galaxies_controller.rb
class GalaxiesController < ApplicationController
  before_action :set_galaxy, only: %i[ show edit update destroy ]

  # GET /galaxies or /galaxies.json
  def index
    @galaxies = Galaxy.all
  end

  # GET /galaxies/1 or /galaxies/1.json
  def show
  end

  # GET /galaxies/new
  def new
    @galaxy = Galaxy.new
  end

  # GET /galaxies/1/edit
  def edit
  end

  # POST /galaxies or /galaxies.json
  def create
    @galaxy = Galaxy.new(galaxy_params)

    respond_to do |format|
      if @galaxy.save
        format.html { redirect_to @galaxy, notice: "Galaxy was successfully created." }
        format.json { render :show, status: :created, location: @galaxy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @galaxy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galaxies/1 or /galaxies/1.json
  def update
    respond_to do |format|
      if @galaxy.update(galaxy_params)
        format.html { redirect_to @galaxy, notice: "Galaxy was successfully updated." }
        format.json { render :show, status: :ok, location: @galaxy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @galaxy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galaxies/1 or /galaxies/1.json
  def destroy
    @galaxy.destroy
    respond_to do |format|
      format.html { redirect_to galaxies_url, notice: "Galaxy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galaxy
      @galaxy = Galaxy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def galaxy_params
      params.require(:galaxy).permit(:name)
    end
end

app/helpers/galaxies_helper.rb
module GalaxiesHelper
end

app/views/galaxies/_form.html.erb
<%= form_with(model: galaxy) do |form| %>
  <% if galaxy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(galaxy.errors.count, "error") %> prohibited this galaxy from being saved:</h2>

      <ul>
        <% galaxy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/galaxies/edit.html.erb
<h1>Editing Galaxy</h1>

<%= render 'form', galaxy: @galaxy %>

<%= link_to 'Show', @galaxy %> |
<%= link_to 'Back', galaxies_path %>

app/views/galaxies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Galaxies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galaxies.each do |galaxy| %>
      <tr>
        <td><%= galaxy.name %></td>
        <td><%= link_to 'Show', galaxy %></td>
        <td><%= link_to 'Edit', edit_galaxy_path(galaxy) %></td>
        <td><%= link_to 'Destroy', galaxy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Galaxy', new_galaxy_path %>

app/views/galaxies/new.html.erb
<h1>New Galaxy</h1>

<%= render 'form', galaxy: @galaxy %>

<%= link_to 'Back', galaxies_path %>

app/views/galaxies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @galaxy.name %>
</p>

<%= link_to 'Edit', edit_galaxy_path(@galaxy) %> |
<%= link_to 'Back', galaxies_path %>