config/routes.rb
Rails.application.routes.draw do
  resources :ingesters
  resources :stargate_manual_overrides
  resources :stargates
  resources :north_stars
  resources :star_nodes
  resources :solar_systems
  resources :galaxies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stargate.rb
class Stargate < ApplicationRecord
end

app/controllers/stargates_controller.rb
class StargatesController < ApplicationController
  before_action :set_stargate, only: %i[ show edit update destroy ]

  # GET /stargates or /stargates.json
  def index
    @stargates = Stargate.all
  end

  # GET /stargates/1 or /stargates/1.json
  def show
  end

  # GET /stargates/new
  def new
    @stargate = Stargate.new
  end

  # GET /stargates/1/edit
  def edit
  end

  # POST /stargates or /stargates.json
  def create
    @stargate = Stargate.new(stargate_params)

    respond_to do |format|
      if @stargate.save
        format.html { redirect_to @stargate, notice: "Stargate was successfully created." }
        format.json { render :show, status: :created, location: @stargate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stargate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stargates/1 or /stargates/1.json
  def update
    respond_to do |format|
      if @stargate.update(stargate_params)
        format.html { redirect_to @stargate, notice: "Stargate was successfully updated." }
        format.json { render :show, status: :ok, location: @stargate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stargate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stargates/1 or /stargates/1.json
  def destroy
    @stargate.destroy
    respond_to do |format|
      format.html { redirect_to stargates_url, notice: "Stargate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stargate
      @stargate = Stargate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stargate_params
      params.require(:stargate).permit(:automatic, :source, :start_id, :end_id, :blocking)
    end
end

app/helpers/stargates_helper.rb
module StargatesHelper
end

app/views/stargates/_form.html.erb
<%= form_with(model: stargate) do |form| %>
  <% if stargate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stargate.errors.count, "error") %> prohibited this stargate from being saved:</h2>

      <ul>
        <% stargate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :automatic %>
    <%= form.check_box :automatic %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :start_id %>
    <%= form.number_field :start_id %>
  </div>

  <div class="field">
    <%= form.label :end_id %>
    <%= form.number_field :end_id %>
  </div>

  <div class="field">
    <%= form.label :blocking %>
    <%= form.check_box :blocking %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stargates/edit.html.erb
<h1>Editing Stargate</h1>

<%= render 'form', stargate: @stargate %>

<%= link_to 'Show', @stargate %> |
<%= link_to 'Back', stargates_path %>

app/views/stargates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stargates</h1>

<table>
  <thead>
    <tr>
      <th>Automatic</th>
      <th>Source</th>
      <th>Start</th>
      <th>End</th>
      <th>Blocking</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stargates.each do |stargate| %>
      <tr>
        <td><%= stargate.automatic %></td>
        <td><%= stargate.source %></td>
        <td><%= stargate.start_id %></td>
        <td><%= stargate.end_id %></td>
        <td><%= stargate.blocking %></td>
        <td><%= link_to 'Show', stargate %></td>
        <td><%= link_to 'Edit', edit_stargate_path(stargate) %></td>
        <td><%= link_to 'Destroy', stargate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stargate', new_stargate_path %>

app/views/stargates/new.html.erb
<h1>New Stargate</h1>

<%= render 'form', stargate: @stargate %>

<%= link_to 'Back', stargates_path %>

app/views/stargates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Automatic:</strong>
  <%= @stargate.automatic %>
</p>

<p>
  <strong>Source:</strong>
  <%= @stargate.source %>
</p>

<p>
  <strong>Start:</strong>
  <%= @stargate.start_id %>
</p>

<p>
  <strong>End:</strong>
  <%= @stargate.end_id %>
</p>

<p>
  <strong>Blocking:</strong>
  <%= @stargate.blocking %>
</p>

<%= link_to 'Edit', edit_stargate_path(@stargate) %> |
<%= link_to 'Back', stargates_path %>